<a href="https://colab.research.google.com/github/Samu24042/Control-no-lineal-de-manipuladores-flexibles-una-gu-a-pr-ctica-con-MATLAB-y-Simulink/blob/main/icd_taller1_python_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **¡¡ ANTES DE EMPEZAR !!**

Deshabilita autocompletar con IA. Esta acción te ayudará a aprender de verdad. Si estás en Colab sigue estos pasos:



1.   Ir a Herramientas \ Configuración \ Asistencia de IA
2.   Desactivar la casilla **"Mostrar autocompletado impulsado por IA"**
3.   Activar la casilla **"Ocultar funciones de IA generativa"**

# **MÓDULO 0: PRIMEROS PASOS CON PYTHON**

Es común usar Excel para analizar datos, pero si el número de datos es grande, Excel se queda corto. En este caso, es conveniente movernos hacia una herramienta más sofisticada, como Python (el lenguaje de programación que usaremos en el curso). Entonces, antes de analizar datos complejos, debemos entender Python. Por fortuna, es un lenguaje muy legible, muy parecido a Matlab.


**0.1 Variables:** En Excel, guardamos datos en celdas (A1, B2). En Python, usamos variables.

In [1]:
# --- VARIABLES ---

# Asignamos variables con el signo '='
# No necesitamos declarar el tipo (int, float); Python lo infiere.

voltaje = 220       # Entero (int)
resistencia = 10.5  # Decimal (float)
sistema_activo = True # Booleano (lógica binaria: 1 o 0)
nombre_pozo = "Pozo Norte-X" # Texto (string)

# La función print() muestra el resultado en pantalla
print("El voltaje es:", voltaje)

# La función type() nos dice qué tipo de dato es
print("Tipo de dato de resistencia:", type(resistencia))

El voltaje es: 220
Tipo de dato de resistencia: <class 'float'>

**0.2 Operaciones Matemáticas y Librerías:** Al igual que Matlab, Python funciona como una calculadora científica:

In [3]:
# --- CÁLCULOS EN PYTHON ---

# Ley de Ohm: I = V / R
corriente = voltaje / resistencia

# Potencia: P = V * I
potencia = voltaje * corriente

print("La corriente calculada es", corriente, "Amperios")
print("La potencia es:", potencia, "Watts")

La corriente calculada es 20.952380952380953 Amperios
La potencia es: 4609.523809523809 Watts

A diferencia de Matlab, la mayoría de funciones de Python están en librerías, y antes de usarlas, debemos importar esas librerías:

In [4]:
# --- LIBRERÍAS ---

# Calculemos el voltaje a partir de la potencia y la resistencia.
# Para ello debemos usar la función "raíz cuadrada", sqrt().
# Esta función está disponible en la librería "math", así que primero debemos importar esta librería.
# Además, podemos darle nombre un "alias" personalizado a la librería, por ejemplo "matem"

import math as matem

# Voltaje calculado: voltaje_calculado = sqrt(potencia*resistencia)
voltaje_calculado = matem.sqrt(potencia*resistencia)

print(f"El voltaje calculado es: {voltaje_calculado:.2f} Voltios") #.2f se usa para mostrar 2 decimales

El voltaje calculado es: 220.00 Voltios

**0.3 Estructuras de Datos: Listas y Diccionarios:**
En ingeniería rara vez trabajamos con un solo dato; trabajamos con vectores o series. En Python, usamos listas (que definimos usando corchetes []) y diccionarios (definidas usando llaves {}).

Las listas son los "vectores" de Pyhton; es decir, colecciones ordenadas indexadas por posición (0,1,2...). Por otro lado, los diccionarios son colecciones desordenadas de pares "llave"-"valor".

**Nota:** En Python, los elementos de las listas se empiezan a contar desde CERO, no desde uno.

In [5]:
# --- LISTAS (VECTORES) ---

# Una lista de temperaturas tomadas por un sensor en 5 momentos distintos
temperaturas = [105.4, 106.2, 108.1, 107.5, 110.0]

# Acceder al primer dato (índice 0)
print("Temperatura inicial:", temperaturas[0])

# Acceder al último dato (índice -1)
print("Temperatura final:", temperaturas[-1])

# ¿Cuántos datos tenemos?
print("Número de mediciones:", len(temperaturas)) #la función len() devuelve el número de elementos de la lista

# Operaciones básicas: Agregar un dato nuevo
temperaturas.append(24.1) #el método .append() agrega un elemento al final de la lista
print("Lecturas actualizadas:", temperaturas)

Temperatura inicial: 105.4
Temperatura final: 110.0
Número de mediciones: 5
Lecturas actualizadas: [105.4, 106.2, 108.1, 107.5, 110.0, 24.1]

In [6]:
# --- DICCIONARIOS (LLAVE-VALOR) ---

# Describamos con un diccionario las propiedades de una turbina
turbina_1 = {
    "id": "T-001",
    "ubicacion": "Sala de Máquinas A",
    "rpm_actual": 3600,
    "temperatura_aceite": 85.5,
}

print("Información de la turbina:", turbina_1)
print("RPM de la turbina:", turbina_1["rpm_actual"])

Información de la turbina: {'id': 'T-001', 'ubicacion': 'Sala de Máquinas A', 'rpm_actual': 3600, 'temperatura_aceite': 85.5}
RPM de la turbina: 3600

**0.4 Identación, Condicionales (if, else) y Ciclos (for):**
A diferencia de otros lenguajes que usan llaves {} para agrupar código, Python utiliza la indentación (sangría). Es obligatorio, no estético.

Cada vez que una línea termina en dos puntos (:), la siguiente línea debe tener identación (usualmente 4 espacios). Todo el código que comparte el mismo nivel de indentación pertenece al mismo bloque lógico.

In [12]:
# --- CONDICIONALES ---

import random # importamos la librería random

retorno_diario = -random.randint(1, 10) # simulamos una caída aleatoria entre el 10% y 1%
print(f"retorno: {retorno_diario} %")

# Noten los dos puntos (:) al final de la línea 'if'
# Noten el espacio (4 espacios o 1 TAB) en las líneas print
if retorno_diario < -5:
    print("ALERTA: Caída significativa detectada.") # esta línea se ejecuta si es TRUE porque está identada respecto al "if"
    print("Revisar noticias macroeconómicas.") # esta línea también se ejecuta si es TRUE porque está identada
else:
    print("Mercado estable.") # esta línea se ejecuta si es FALSE porque está identada respecto al "else"

print("Fin del análisis.") # Esta línea se ejecuta SIEMPRE, porque no tiene indentación.

retorno: -9 %
ALERTA: Caída significativa detectada.
Revisar noticias macroeconómicas.
Fin del análisis.

In [13]:
# --- CICLOS ---

# Caso1: Usemos un ciclo for para operar sobre una lista
precios_USD = [100, 102, 98, 105, 110] # lista de precios en dolares
precios_COP = []

# "Para cada 'precio' dentro de la lista 'precios'..."
for precio in precios_USD:
    # Lo convertimos a pesos (multiplicamos por 3650)
    precio_COP = precio*3650
    precios_COP.append(precio_COP)

print("Lista de precios en pesos es", precios_COP)

Lista de precios en pesos es [365000, 372300, 357700, 383250, 401500]

In [14]:
# Caso 2: Si no tienes una lista, pero quieres repetir algo 5 veces, usas la función range()
for numero in range(5): # range(5) crea una secuencia: 0, 1, 2, 3, 4
    print(f"Vuelta número: {numero}")

Vuelta número: 0
Vuelta número: 1
Vuelta número: 2
Vuelta número: 3
Vuelta número: 4

In [15]:
# Caso 3: Usemos ahora un ciclo for para operar sobre un diccionario
ventas = {
    "Lunes": 100,
    "Martes": 250,
    "Miércoles": 180
}

# Si queremos recorrer el diccionario sobre las LLAVES:
for dia in ventas.keys():
  print(f"El día {dia} se registraron ventas")

# Si queremos recorrer el diccionario sobre los VALORES:
total_ventas = 0
for valor in ventas.values():
  total_ventas = total_ventas + valor
print(f"El total de ventas de la semana fue {total_ventas}")

El día Lunes se registraron ventas
El día Martes se registraron ventas
El día Miércoles se registraron ventas
El total de ventas de la semana fue 530

**Nota:** Aunque el ciclo for es fundamental para entender la lógica, en Ciencia de Datos intentamos evitarlo cuando procesamos millones de datos. Preferimos la "vectorización" (operar sobre toda la columna a la vez). Esto lo veremos en el Módulo 1 (Pandas).

# Reto 1 (motor industrial):
Tienes una lista de lecturas crudas provenientes de un sensor de vibración en un motor industrial. Sin embargo, el sensor a veces falla y arroja valores negativos (ruido/error) o valores extremadamente altos (posible falla crítica). Tu tarea es implementar un código que haga lo siguiente:


* Crea una lista con los datos válidos (aquellos que no son negativos)
* Calcula el valor $RMS$ de los datos válidos y "normales", ignorando aquellos que son mayores que 100 (estos corresponden a posibles fallas crítica del motor). Recuerda que $RMS = \sqrt{\frac{x^2}{n}}$.
* Finalmente, crea un diccionario llamado "reporte" que contenga:
    * la lista de datos válidos
    * el total de datos válidos
    * el total de alertas críticas
    * el valor RMS calculado
* Imprime el reporte

In [23]:
# --- DATOS DE ENTRADA (NO MODIFICAR) ---
lecturas_vibracion = [10.5, 12.1, -5.0, 11.8, 105.4, 13.2, -1.2, 12.5, 11.0, 9.8]

# --- TU CÓDIGO EMPIEZA AQUÍ ---

import math

datos_validos = [i for i in lecturas_vibracion if i >= 0]

alertas_criticas = len([i for i in datos_validos if i > 100])

datos_normales = [i for i in datos_validos if i <= 100]

# Calculo del RMS
if len(datos_normales) > 0:
    suma_cuadrados = sum(i**2 for i in datos_normales)
    rms = math.sqrt(suma_cuadrados / len(datos_normales))
else:
    rms = 0

reporte = {
    "datos_validos": datos_validos,
    "total_datos_validos": len(datos_validos),
    "total_alertas_criticas": alertas_criticas,
    "valor_rms": rms
}
print(reporte)

{'datos_validos': [10.5, 12.1, 11.8, 105.4, 13.2, 12.5, 11.0, 9.8], 'total_datos_validos': 8, 'total_alertas_criticas': 1, 'valor_rms': 11.609294306102946}

# Reto 2 (controlador de batería):


Eres el ingeniero a cargo de una micro-red eléctrica que alimenta una fábrica. Tienes paneles solares y una batería de respaldo. Tu objetivo es minimizar el costo de la energía comprada a la red externa simulando 10 horas de operación.

**Reglas del Sistema:**

1.  Si en cierta hora hay excedente de generación:
    * La energía sobrante carga la batería.
    * La batería no puede superar los 50 KWh. Si se llena, el resto se pierde.
3.  Si hay déficit de generación:
    * La energía faltante se toma primero de la batería.
    * Si la batería se agota (o no alcanza), la diferencia se compra a la red eléctrica.
    * La batería no puede quedar con carga negativa (mínimo 0 kWh).
4.  Las tarifas de la energía de la red son dinámicas:
    * El costo en horario pico (10:00 am, 11:00 am y 12:00 m) es de 500 COP/kWh.
    * En hora valle (resto de horas), el costo es de 200 COP/kWh.

**Objetivo:**
Recorre las listas, aplica la lógica hora por hora y genera un diccionario final con el reporte de los resultados acumulados.

In [25]:
# --- DATOS DE ENTRADA (NO MODIFICAR) ---
# La resolución de los datos es horaria empezando desde las 7:00 am
generacion = [15.0, 20.0, 45.0, 55.0, 60.0, 40.0, 25.0, 10.0, 5.0, 0.0] # kWh producidos
consumo    = [10.0, 15.0, 20.0, 70.0, 80.0, 50.0, 40.0, 25.0, 20.0, 10.0] # kWh consumidos

# --- PARÁMETROS DEL SISTEMA ---
capacidad_bateria = 50.0  # kWh máximos
carga_actual      = 10.0  # La batería inicia con 10 kWh
dinero_gastado    = 0.0   # Acumulador de dinero

# historial de carga de la batería
historial_bateria = []

# --- TU CÓDIGO EMPIEZA AQUÍ ---

hora_inicial = 7

for i in range(len(generacion)):
    hora_actual = hora_inicial + i
    energia_generada = generacion[i]
    energia_consumida = consumo[i]

    balance = energia_generada - energia_consumida

    if hora_actual in [10, 11, 12]:
        tarifa = 500
    else:
        tarifa = 200

    if balance > 0:
        espacio_disponible = capacidad_bateria - carga_actual
        energia_a_cargar = min(balance, espacio_disponible)
        carga_actual += energia_a_cargar
    else:
        deficit = abs(balance)
        energia_de_bateria = min(deficit, carga_actual)
        carga_actual -= energia_de_bateria
        deficit_restante = deficit - energia_de_bateria

        if deficit_restante > 0:
            dinero_gastado += deficit_restante * tarifa

    historial_bateria.append(carga_actual)

# --- REPORTE FINAL ---
reporte = {
    "Costo Total Operación ($)": dinero_gastado,
    "Carga Final Batería (kWh)": carga_actual,
    "Historial Batería": historial_bateria
}

print("--- REPORTE DE GESTIÓN ENERGÉTICA ---")
print(reporte)

--- REPORTE DE GESTIÓN ENERGÉTICA ---
{'Costo Total Operación ($)': 11000.0, 'Carga Final Batería (kWh)': 0.0, 'Historial Batería': [15.0, 20.0, 45.0, 30.0, 10.0, 0.0, 0.0, 0.0, 0.0, 0.0]}

# **MÓDULO 1: INTRODUCCIÓN A PANDAS**

Las listas y diccionarios de Python son útiles, pero para trabajar con datos a un nivel más avanzado necesitamos algo más eficiente. Aquí entra Pandas, una librería de Python diseñada para trabajar con datos.

Pandas introduce el DataFrame: Es una tabla con etiquetas (filas y columnas), donde los tipos de datos están optimizados para manejar millones de registros. Es como una hoja de Excel, pero eficiente y programable. Al igual que en Excel, en un DataFrame se pueden almacenar datos de diferentes tipos: números, fechas, strings, etc.


**1.1 Preliminares:**
Primero, importamos la librería y descargamos los datos con los que trabajaremos: las notas de un curso avanzado en topología variacional.

In [26]:
# --- IMPORTAR PANDAS ---

import pandas as pd # Importamos la librería con el alias 'pd' (estándar mundial)


# --- CARGAR DATOS ---

# 1. DEFINICIÓN DE LA FUENTE DE DATOS
# ID del archivo donde están las notas:
sheet_id = "1mZJTauwhpKWSJ5d6LxH1wnJ1GNC_Dact0_5yG6p8OZg"
# Construimos la URL de exportación del archivo (el archivo está disponible en Google Drive):
url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/export?format=csv"

# 2. CARGA DEL DataFrame
# Construimos nuestro DataFrame, llamado "df_notas", leyendo el archivo desde la URL:
df_notas = pd.read_csv(url)


# Veamos cómo es el DataFrame que acabamos de descargar:
display(df_notas)

       Estudiante     Estado  Parcial 1  Parcial 2  Parcial 3
0           Gohan     becado        5.0        4.8        5.0
1           Bulma  no_becado        5.0        5.0        5.0
2          Vegeta     becado        4.2        4.5        4.7
3            Goku     becado        3.0        3.5        4.1
4         Piccolo  no_becado        4.0        4.2        3.9
5         Krillin  no_becado        3.2        2.8        3.0
6          Yamcha     becado        1.5        1.0        0.8
7    Ten Shin Han     becado        3.8        3.9        4.0
8        Mr. Popo  no_becado        2.5        2.0        1.5
9   Maestro Roshi     becado        4.5        1.2        3.0
10         Trunks  no_becado        4.0        4.1        4.3
11          Goten  no_becado        3.5        3.2        3.8
12          Videl     becado        4.7        4.6        4.8
13      Mr. Satan  no_becado        0.5        1.0        1.2
14      Majin Boo     becado        1.0        0.0        2.5
15        Freezer  no_becado        4.8        4.9        1.5
16           Cell     becado        4.5        4.7        4.6
17    Androide 17  no_becado        3.5        3.5        3.5
18    Androide 18  no_becado        3.8        3.9        4.1
19        Bardock  no_becado        3.0        3.0        3.1
20         Raditz  no_becado        2.0        1.5        0.5
21          Nappa     becado        1.8        2.0        1.5
22          Broly  no_becado        0.0        0.0        5.0
23          Dende  no_becado        5.0        1.0        5.0
24        Dodoria  no_becado        5.0        5.0        5.0

**1.2 Exploración de Datos:**
Antes de analizar, debemos entender qué forma tienen nuestros datos:
* `.shape`: Nos dice cuántas filas (estudiantes) y columnas tenemos.
* `.describe()`: Nos da estadísticas rápidas (nota máxima, mínima, promedio por parcial).
* `.dtypes`: Nos dice qué tipo de datos tenemos (números o texto).

In [ ]:
# Ver dimensiones (Filas, Columnas)
print(f"Dimensiones de los datos: {df_notas.shape}")

# Ver tipos de datos
print("\n--- Tipos de datos ---")
print(df_notas.dtypes)

# Estadísticas básicas
print("\n--- Estadísticas del Curso ---")
# describe() nos dará la media, desviación estándar, min, max y cuartiles
display(df_notas.describe())

**1.3 Etiquetas:**
Las columnas y filas de los **DataFrames** tienen etiquetas que nos ayudan a identificarlas:

* **Etiquetas de columna:** Generalmente son los nombres de las variables almacenadas (ej. `Edad`, `Precio`).
* **Etiquetas de fila (Índice):** Actúan como el identificador único de cada fila. Comúnmente son números consecutivos, pero también pueden ser fechas (en series temporales) o textos específicos.

Una característica clave es que las columnas pueden almacenar **diferentes tipos de datos**. Por ejemplo, la primera columna puede contener números enteros y la segunda cadenas de texto (*strings*).

In [27]:
# --- ETIQUETAS DEL DataFrame ---

print("\n--- NOMBRES DE COLUMNAS ---")
print(df_notas.columns) # Muestra los nombres de las variables
# En nuesto caso, los nombres de las columnas son: "nombre", "estado", "parcial 1", ...


print("\n--- ÍNDICE (ETIQUETAS DE FILAS) ---")
print(df_notas.index) # Muestra cómo están etiquetadas las filas
# En nuesto caso, la etiqueta de la filas es la posición que ocupa en la tabla (empezando por 0)

--- NOMBRES DE COLUMNAS ---
Index(['Estudiante', 'Estado', 'Parcial 1', 'Parcial 2', 'Parcial 3'], dtype='object')

--- ÍNDICE (ETIQUETAS DE FILAS) ---
RangeIndex(start=0, stop=25, step=1)

**1.4 Creación de Nuevas Columnas:**
Vamos a calcular la **Nota Definitiva** de cada estudiante.
Asumiremos que el promedio es la suma de los tres parciales dividida entre 3.

$$\text{Promedio} = \frac{\text{Parcial 1} + \text{Parcial 2} + \text{Parcial 3}}{3}$$

In [28]:
# Crear la columna 'Definitiva' promediando los 3 parciales
df_notas['Definitiva'] = (df_notas['Parcial 1'] + df_notas['Parcial 2'] + df_notas['Parcial 3']) / 3

# Redondeamos a 1 decimal para que se vea mejor
df_notas['Definitiva'] = df_notas['Definitiva'].round(1)

# Mostramos el resultado con la nueva columna
print("--- Notas con Definitiva Calculada ---")
display(df_notas.head(4)) # .head(n) muestra las n primeras filas del DataFrame

--- Notas con Definitiva Calculada ---

  Estudiante     Estado  Parcial 1  Parcial 2  Parcial 3  Definitiva
0      Gohan     becado        5.0        4.8        5.0         4.9
1      Bulma  no_becado        5.0        5.0        5.0         5.0
2     Vegeta     becado        4.2        4.5        4.7         4.5
3       Goku     becado        3.0        3.5        4.1         3.5

**1.5 Filtrado de Datos:**
Ahora responderemos preguntas específicas sobre el curso:
1. ¿Quiénes perdieron la materia? (Nota < 3.0)
2. ¿Quiénes son los estudiantes de excelencia? (Nota > 4.5)

In [29]:
# 1. Estudiantes que reprobaron (Definitiva menor a 3.0)

# Esto devuelve un DataFrame sólo con las filas que cumplen la condición:
reprobados = df_notas[df_notas['Definitiva'] < 3.0]

print(f"Número de estudiantes reprobados: {len(reprobados)}")
print("\n--- Lista de Reprobados ---")
display(reprobados[['Estudiante', 'Definitiva']]) # Solo mostramos nombre y nota


# 2. Estudiantes de Excelencia (Definitiva mayor a 4.5)
excelencia = df_notas[df_notas['Definitiva'] > 4.5]

print("\n--- Cuadro de Honor (Excelencia) ---")
display(excelencia[['Estudiante', 'Definitiva']])

Número de estudiantes reprobados: 8

--- Lista de Reprobados ---

       Estudiante  Definitiva
6          Yamcha         1.1
8        Mr. Popo         2.0
9   Maestro Roshi         2.9
13      Mr. Satan         0.9
14      Majin Boo         1.2
20         Raditz         1.3
21          Nappa         1.8
22          Broly         1.7

--- Cuadro de Honor (Excelencia) ---

   Estudiante  Definitiva
0       Gohan         4.9
1       Bulma         5.0
12      Videl         4.7
16       Cell         4.6
24    Dodoria         5.0

**1.6 Ordenamiento:** Vamos a ordenar la lista completa del mejor al peor promedio para ver el ranking final del curso.

In [31]:
# Ordenar por 'Definitiva' de forma descendente (el más alto primero)
ranking = df_notas.sort_values(by='Definitiva', ascending=False)

print("--- Top 5 Mejores Estudiantes ---")
display(ranking.head(5))

print("\n--- Los 5 con rendimiento más bajo ---")
display(ranking.tail(5))

--- Top 5 Mejores Estudiantes ---

   Estudiante     Estado  Parcial 1  Parcial 2  Parcial 3  Definitiva
1       Bulma  no_becado        5.0        5.0        5.0         5.0
24    Dodoria  no_becado        5.0        5.0        5.0         5.0
0       Gohan     becado        5.0        4.8        5.0         4.9
12      Videl     becado        4.7        4.6        4.8         4.7
16       Cell     becado        4.5        4.7        4.6         4.6

--- Los 5 con rendimiento más bajo ---

   Estudiante     Estado  Parcial 1  Parcial 2  Parcial 3  Definitiva
22      Broly  no_becado        0.0        0.0        5.0         1.7
20     Raditz  no_becado        2.0        1.5        0.5         1.3
14  Majin Boo     becado        1.0        0.0        2.5         1.2
6      Yamcha     becado        1.5        1.0        0.8         1.1
13  Mr. Satan  no_becado        0.5        1.0        1.2         0.9

**1.7 Consultas y Selección de Datos por Posición (.iloc):**
En Pandas podemos acceder a los datos de un DataFrame especificando la posición que ocupan. Es decir, mediante sus coordenadas.


*   *Ejemplo:* "Dame el dato que está en la fila 2, columna 0".

La sintaxis es: `df_notas.iloc[numero_fila, numero_columna]`

Recordemos que en Python los conteos empiezan en **0**.

In [32]:
# 1. Dato específico: Fila 0 (Primer estudiante), Columna 0 (Primer parcial)
dato_posicion = df_notas.iloc[0, 0]
print(f"Dato en fila 0, col 0 (Nombre del primer alumno en la lista): {dato_posicion}")

# 2. Última fila del curso (útil cuando no sabemos cuántos hay)
print("\n--- Datos del último estudiante de la lista ---")
print(df_notas.iloc[-1]) # -1 significa "el último"

# 3. Slicing
# Las notas obtenidas por los 5 primeros estudiantes (filas 0 a 4) en los 3 parciales (columnas 2 a 4)
print("\n--- Subconjunto (Parciales de los 5 primeros estudiantes en la lista) ---")
# OJO: En .iloc, el límite superior NO se incluye. Ej: 2:5 cubre las posiciones 2, 3 y 4
display(df_notas.iloc[0:5, 2:5])

Dato en fila 0, col 0 (Nombre del primer alumno en la lista): Gohan

--- Datos del último estudiante de la lista ---
Estudiante      Dodoria
Estado        no_becado
Parcial 1           5.0
Parcial 2           5.0
Parcial 3           5.0
Definitiva          5.0
Name: 24, dtype: object

--- Subconjunto (Parciales de los 5 primeros estudiantes en la lista) ---

   Parcial 1  Parcial 2  Parcial 3
0        5.0        4.8        5.0
1        5.0        5.0        5.0
2        4.2        4.5        4.7
3        3.0        3.5        4.1
4        4.0        4.2        3.9

# Reto 3 (módulo Pandas)

## Problema 1. Estudiantes para Refuerzo

Escribe un código que muestre los estudiantes que necesitan refuerzo. Esto es, los estudiantes que tienen notas entre 3 y 3.5.

**Entregable:** Lista que muestre únicamente el nombre de los estudiantes que necesitan refuerzo.

In [33]:
# --- CÓDIGO PROBLEMA 1 ---
df_notas["Promedio"] = df_notas[["Parcial 1", "Parcial 2", "Parcial 3"]].mean(axis=1)

refuerzo = df_notas.loc[
    df_notas["Promedio"].between(3, 3.5),
    "Estudiante"
].tolist()

print(refuerzo)

['Krillin', 'Goten', 'Androide 17', 'Bardock']

## Problema 2. El Estudiante Promedio

Bills, el Dios de la Destrucción, quiere eliminar a la mitad del curso. Quiere perdonarle la vida **exactamente al estudiante que esté en la mitad de la tabla** según su **Nota Definitiva**.

Si ordenamos a los estudiantes del mejor al peor... ¿Quién es el estudiante que ocupa la posición exacta de la mitad?

**Entregable (sin contar manualmente):** Nombre del estudiante que está en la mitad de la tabla de resultados.

In [37]:
# --- CÓDIGO PROBLEMA 2 ---

df_notas["Nota Definitiva"] = df_notas[["Parcial 1", "Parcial 2", "Parcial 3"]].mean(axis=1)
df_ordenado = df_notas.sort_values(by="Nota Definitiva", ascending=False).reset_index(drop=True)
estudiante_mitad = df_ordenado.loc[len(df_ordenado) // 2, "Estudiante"]

print(estudiante_mitad)

Goku

## Problema 3. Los 3 Peores Resultados del Parcial 3

Queremos saber quiénes fueron los **3 peores resultados** en el **Parcial 3**, pero solo nos interesa ver sus nombres y la nota de ese parcial.

In [38]:
# --- CÓDIGO PROBLEMA 3 ---

df_peores = df_notas.sort_values(by="Parcial 3", ascending=True)
resultado = df_peores[["Estudiante", "Parcial 3"]].head(3)

print(resultado)

   Estudiante  Parcial 3
20     Raditz        0.5
6      Yamcha        0.8
13  Mr. Satan        1.2

## Problema 4. Premio al Esfuerzo

Hay que seleccionar a uno de los estudiantes para otorgarle el **Premio al Esfuerzo**. Intentamos exaltar al estudiante que más haya progresado durante el curso. Claro está, es requisito que ese estudiante haya aprobado el curso.

**Entregable:** Proponga un método para medir el **progreso** de cada estudiante. Implemente el código de su propuesta y determine el estudiante merecedor del premio.

In [42]:
# --- METODO PROPUESTO ---
# El progreso se medira como la diferencia entre el Parcial 3 y el Parcial 1.
# Esto permite ver cuanto mejoro el estudiante desde el inicio hasta el final del curso.
# Solo se tendran en cuenta los estudiantes que aprobaron.

# --- CÓDIGO PROBLEMA 4 ---

df_notas["Progreso"] = df_notas["Parcial 3"] - df_notas["Parcial 1"]
aprobados = df_notas[df_notas["Nota Definitiva"] >= 3.0]
ganador = aprobados.sort_values(by="Progreso", ascending=False).iloc[0]

print("Premio al Esfuerzo:")
print(ganador["Estudiante"])

Premio al Esfuerzo:
Goku

## Problema 5. Nuevo Sistema Para el Cálculo de la Nota Definitiva

Se ha decidido que los exámenes no valen lo mismo. Para calcular la nota final, se debe usar la siguiente ponderación:
* **Parcial 1:** Vale el **20%**
* **Parcial 2:** Vale el **30%**
* **Parcial 3:** Vale el **50%**

Además, la nota debe aproximarse al "medio punto" más cercano (0.0, 0.5, 1.0, 1.5, etc.)

**Entregable:** Crea una nueva columna llamada `Definitiva_v2` que aplique estos porcentajes. Además, muestra los resultados de los 5 primeros estudiantes de la lista con su respectivo nombre.

In [45]:
# --- CÓDIGO PROBLEMA 5 ---

df_notas["Definitiva_v2"] = (
    df_notas["Parcial 1"] * 0.20 +
    df_notas["Parcial 2"] * 0.30 +
    df_notas["Parcial 3"] * 0.50
)

df_notas["Definitiva_v2"] = (df_notas["Definitiva_v2"] * 2).round() / 2
top_5 = df_notas.sort_values(by="Definitiva_v2", ascending=False)
resultado = top_5[["Estudiante", "Definitiva_v2"]].head(5)

print(resultado)

   Estudiante  Definitiva_v2
0       Gohan            5.0
1       Bulma            5.0
24    Dodoria            5.0
12      Videl            4.5
2      Vegeta            4.5